In [ ]:
import math

def basic_sigmoid(x):
  """
  Compute sigmoid of x.

  Args:
  x -- A scalar

  Return:
  s -- sigmoid(x)
  """

  s = 1 / (1 + math.exp(-x))
  return s

In [ ]:
import numpy as np

x= np.array([1,2,3])
print(np.exp(x)) #result is (exp(1) (exp(2) (exp(3))))

[ 2.71828183  7.3890561  20.08553692]


In [ ]:
x= np.array([1,2,3])
print(x+3)

[4 5 6]


In [ ]:
def basic_sigmoid(X):
  """
  Compute sigmoid of x.

  Args:
  x -- A scalar

  Return:
  s -- sigmoid(x)
    X:
  """

  ### start code here

  s=1/(1+np.exp(-X))
  return s

In [ ]:
def basic_sigmoid(X):
  """
  Compute sigmoid of x.

  Args:
  x -- A scalar

  Return:
  s -- sigmoid(x)
    X:
  """

  ### start code here

  s=1/(1+np.exp(-X))

  x= np.array([1,2,3])
  print("sigmoid_derivative(x) = " + str(sigmoid_derivative(x)))
  return s

def sigmoid_derivative(x):
  """
  Compute the gradient (also called the slope or derivative) of the sigmoid function evaluated at x.

  Arguments:
  x -- A scalar or numpy array

  Return:
  ds -- Your computed gradient.
  """

  s = 1/(1+np.exp(-x))
  ds = s*(1-s)
  return ds

In [ ]:
def image2vector(image):
  """
  Argument:
  image -- a numpy array of shape (length, height, depth)

  Returns:
  v -- a vector of shape (length*height*depth, 1)
  """
  v = image.reshape((image.shape[0]*image.shape[1]*image.shape[2],1))
  return v

In [ ]:
#this is a 3 by 3 by 2 array, typyically images will be (num_px_x, num_px_y)
image = np.array([[[0.67861392, 0.29380381],
                  [0.90714982, 0.52835647],
                  [0.42152512, 0.45017551]],

                 [[0.92814219, 0.98667762],
                  [0.85320470, 0.52351845],
                  [0.19988212, 0.22973712]],

                 [[0.67373664, 0.78836664],
                  [0.88976655, 0.98876765],
                  [0.97746733,0.76355456]]])

print("image2vector(image) = " + str(image2vector(image)))

image2vector(image) = [[0.67861392]
 [0.29380381]
 [0.90714982]
 [0.52835647]
 [0.42152512]
 [0.45017551]
 [0.92814219]
 [0.98667762]
 [0.8532047 ]
 [0.52351845]
 [0.19988212]
 [0.22973712]
 [0.67373664]
 [0.78836664]
 [0.88976655]
 [0.98876765]
 [0.97746733]
 [0.76355456]]


In [ ]:
def noramlizeRows(x):
  """
  Implement a function that normalizes each row of the matrix x (to have unit length).

  Argument:
  x -- A numpy matrix of shape (n, m)

  Returns:
  x -- The normalized (by row) numpy matrix. You
  """
  x_norm = np.linalg.norm(x,axis=1,keepdims=True)
  x = x/x_norm
  return x

In [ ]:
x = np.array([[0,1000,4000],
             [2,6,4]])
print("noramlizeRows(x) = " + str(noramlizeRows(x)))

noramlizeRows(x) = [[0.         0.24253563 0.9701425 ]
 [0.26726124 0.80178373 0.53452248]]


In [ ]:
def softmax(x):
  """
calculates the softmax for each row of the input x.
  Args:
    x: A numpy matrix of shape (n,m)

  Returns:
    s: A numpy matrix equal to the softmax of x, of shape (n,m)
  """
  x_exp = np.exp(x)
  x_sum = np.sum(x_exp,axis=1,keepdims=True)
  s = x_exp/x_sum
  return s

In [ ]:
x= np.array([
  [9,2,5,0,0],
  [7,5,0,0,0]])
print("softmax(x) = " + str(softmax(x)))

softmax(x) = [[9.80897665e-01 8.94462891e-04 1.79657674e-02 1.21052389e-04
  1.21052389e-04]
 [8.78679856e-01 1.18916387e-01 8.01252314e-04 8.01252314e-04
  8.01252314e-04]]


###Vectorization

In [ ]:
import time

x1 = [9,2,5,0,0,7,5,0,0,9,2,5,0,0]
x2 = [9,2,2,9,0,9,2,5,0,0,9,2,5,0]
### CLASSIC DOT PRODUCT OF VECTORS IMPLEMENTATION ###
tic = time.process_time()
dot = 0
for i in range(len(x1)):
  dot+= x1[i]*x2[i]
toc = time.process_time()

print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

###vectorized outer product
tic = time.process_time()
outer = np.zeros((len(x1),len(x2)))
for i in range(len(x1)):
  for j in range(len(x2)):
    outer[i,j] = x1[i]*x2[j]
    toc = time.process_time()
print ("outer = " + str(outer) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

###classic elementwise implementation
tic = time.process_time()
ele = np.zeros((len(x1),len(x2)))
for i in range(len(x1)):
  for j in range(len(x2)):
    ele[i,j] = x1[i]*x2[j]
    toc = time.process_time()
print ("elementwise = " + str(ele) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")



dot = 196
 ----- Computation time = 0.22058899999954917ms
outer = [[81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [63. 14. 14. 63.  0. 63. 14. 35.  0.  0. 63. 14. 35.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
 ----- Computation time = 0.6466499999993047ms
elementwise = [[81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 

In [ ]:
import time
import numpy as np

x1 = np.random.rand(1000)
x2 = np.random.rand(1000)

### CLASSIC DOT PRODUCT OF VECTORS IMPLEMENTATION ###
tic = time.process_time()
dot = 0
for i in range(len(x1)):
  dot+= x1[i]*x2[i]
toc = time.process_time()

print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

dot = 248.48700709998997
 ----- Computation time = 0.9026279999995168ms
